Readme:
Install node (javascript):
sudo apt-get update
sudo apt-get install nodejs

Install npm package manager:
sudo apt-get install npm

run:

To install project dependend node modules-
npm install

Running the local host and exposing it to public ip (The shell script)-
node index.js 8080 & ./ngrok http 8080

copy and paste the ip into the android studio manager

